COPYPATH("0:/circ.ks","1:/").
COPYPATH("0:/dv.ks","1:/").
COPYPATH("0:/node.ks","1:/").
COPYPATH("0:/node_rcs.ks","1:/").
COPYPATH("0:/print_node_orbit.ks","1:/").
COPYPATH("0:/rdz_dock.ks","1:/").
COPYPATH("0:/rdz_nodock.ks","1:/").
COPYPATH("0:/reentry.ks","1:/").
COPYPATH("0:/reentry_vel.ks","1:/").
COPYPATH("0:/sb.ks","1:/").
COPYPATH("0:/science.ks","1:/").
COPYPATH("0:/science_timing.ks","1:/").
COPYPATH("0:/test_orbit_match.ks","1:/force_orbit_match.ks").